[package]
name = "ironcrypt"
version = "0.1.0"
authors = ["Paterne G. G."]
edition = "2021"
description = "Une librairie Rust pour le hachage et le chiffrement de mots de passe sécurisés."
categories = []
license = "MIT"
repository = "https://github.com/teamflp/ironcrypt"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
argon2 = "0.5.3"
base64 = "0.22.1"
rsa = { version = "0.9.6", features = ["pem"] }
serde_json = "1.0"
sha2 = "0.10.6"
rand = "0.8.5" 
rand_chacha = "0.3.1"
rand_core = "0.6.4"

[dev-dependencies]
criterion = "0.5.0"
