[package]
name = "ironcrypt"
version = "0.1.0"
authors = ["Paterne G. G."]
edition = "2021"
description = "IronCrypt est une librairie Rust dédiée au hachage sécurisé des mots de passe, à la génération de clés RSA, ainsi qu'à la gestion de l'encryption et de la vérification des mots de passe."
keywords = ["cryptography", "RSA", "security", "Rust"]
categories = ["cryptography"]
readme = "README.md"
license = "MIT"
documentation = "https://github.com/teamflp/ironcrypt#readme"
repository = "https://github.com/teamflp/ironcrypt"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
argon2 = "0.5.3"
base64 = "0.22.1"
rsa = { version = "0.9.6", features = ["pem"] }
serde_json = "1.0"
sha2 = "0.10.6"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
clap = { version = "4.5.20", features = ["derive"] }
clap_derive = "4.5.18"
thiserror = "1.0.64"
indicatif = "0.17.8"
aes-gcm = "0.10.3"
aes = "0.8"
cipher = "0.4.4" # Pour le chiffrement symétrique
unicode-general-category = "0.6.0"

[lib]
name = "ironcrypt"
path = "src/lib.rs"

[[bin]]
name = "ironcrypt-cli"
path = "src/main.rs"
