services:

  ironcrypt:
    build: .
    container_name: ironcrypt
    ports:
      - "${IRONCRYPT_PORT}:${IRONCRYPT_PORT}"
      - "${IRONCRYPT_METRICS_PORT}:${IRONCRYPT_METRICS_PORT}"
    environment:
      IRONCRYPT_PORT: "${IRONCRYPT_PORT}"
      IRONCRYPT_METRICS_ENABLED: "${IRONCRYPT_METRICS_ENABLED}"
      IRONCRYPT_METRICS_PORT: "${IRONCRYPT_METRICS_PORT}"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yml.template
    env_file: .env
      volumes:
        - ./loki/loki-config.yml.template:/etc/loki/local-config.yml.template:ro
        - ./loki/loki-data/chunks:/loki/chunks
        - ./loki/loki-data/index:/loki/index
        - ./loki/loki-data/cache:/loki/boltdb-cache
        - ./loki/loki-data/compactor:/loki/compactor
        - ./loki/entrypoint.sh:/entrypoint.sh:ro
      entrypoint: /entrypoint.sh
      ports:
        - "3100:3100"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    env_file: .env
    volumes:
      - ./alertmanager/config.yml.template:/etc/alertmanager/config.yml.template:ro
      - ./alertmanager/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    ports:
      - "9093:9093"


